/*----------------------------------------------------------------------------------------
                            -- HELVETIA SKYTOURS --
   Objet  : Création des tables 

   Auteurice: Venera Ramiqi
   Fait le 20 Fèvrier 2026

----------------------------------------------------------------------------------------


--01 Le pays doit obligatoiremen être en suisse 
--02 Le formatage du téléphone doit être mise sous cette forme +41.__.___.__.__
--03 Le formatage du courriel doit être mise sous cette forme %@%.%
--04 La taille du passager ne doit pas dépasser les 200 cm
--05 Le poids du passager ne doit pas dépasser les 100kg 
--06 Le poids du bagage de ne doit pas dépasser les 28kg
--07 Il faut un minimum de 1 passager estime pour la réservation 

*/



DROP TABLE HS_PASSAGERS_TRAJETS;
DROP TABLE HS_TRAJET; 
DROP TABLE HS_RESERVATION;
DROP TABLE HS_VILLE;
DROP TABLE HS_CLIENT;
DROP TABLE HS_PASSAGERS;
DROP TABLE HS_HELICOPTERE;
DROP TABLE HS_PILOTE;
DROP TABLE HS_ADRESSE;
DROP TABLE HS_PARAMETRE;


create table HS_PARAMETRE(
Taux_accompte number(4,2),
prix_billet_enfant number(6,2),
prix_billet_adulte number(6,2),
tarfi_par_km number(4,2)
);
----
CREATE TABLE HS_ADRESSE(
ADR_ID NUMBER(4)
  CONSTRAINT   PK_HS_ADRESSE PRIMARY KEY ,
ADR_RUE  VARCHAR2(50),
ADR_VILLE VARCHAR2(50),
ADR_NUM NUMBER(4),
ADR_PAYS VARCHAR2(50)
  CONSTRAINT CK_ADR_PAYS CHECK (ADR_PAYS LIKE 'Suisse') --01
);


-----

CREATE TABLE HS_PILOTE(
PILO_ID NUMBER(8)
  CONSTRAINT PK_HS_PILOTE PRIMARY KEY,
PILO_ADR_ID NUMBER(4)
  CONSTRAINT   FK_HS_ADRESSE REFERENCES HS_ADRESSE(ADR_ID),
PILO_NOM VARCHAR2(50)
   CONSTRAINT NN_PILO_NOM NOT NULL,
PILO_PRENOM VARCHAR2(50)
   CONSTRAINT NN_PILO_RPENOM NOT NULL,
PILO_TEL VARCHAR2(17)
   CONSTRAINT NN_PILO_TEL NOT NULL
      CONSTRAINT CK__PILO_TEL CHECK (PILO_TEL LIKE '+41.__.___.__.__'), --02
PILO_EMAIL VARCHAR2(50)
   CONSTRAINT NN_PILO_EMAIL NOT NULL
   CONSTRAINT CK__PILO_EMAIL CHECK (PILO_EMAIL LIKE '%@%.%') --03
);

----
CREATE TABLE HS_HELICOPTERE(
HELI_ID NUMBER(4)
  CONSTRAINT PK_HS_HELICOPTERE PRIMARY KEY, --11
PILO_HELI_ID NUMBER(8)
  CONSTRAINT FK_HS_PILO_HELI REFERENCES HS_PILOTE(PILO_ID), --11
HELI_PLAQUE VARCHAR2(30),
HELI_MODELE VARCHAR2(50),
HELI_CAPACITEMAX NUMBER(2)
   CONSTRAINT NN_HELI_CAPACITEMAX NOT NULL,
HELI_POIDSMAX NUMBER(4)
   CONSTRAINT NN_HELI_POIDSMAX NOT NULL
);


----
CREATE TABLE HS_PASSAGERS(
PASS_ID NUMBER(8)
  CONSTRAINT PK_HS_PASSAGERS PRIMARY KEY,
PASS_TAILLE NUMBER(4)
  CONSTRAINT NN_PASS_TAILLE NOT NULL
  CONSTRAINT CK_PASS_TAILLE CHECK (PASS_TAILLE <= 200), --04
PASS_POIDS NUMBER(4)
  CONSTRAINT NN_PASS_POIDS NOT NULL
  CONSTRAINT CK_PASS_POIDS CHECK (PASS_POIDS <= 100), --05
PASS_POIDSBAGAGE NUMBER(4)
  CONSTRAINT NN_PASS_POIDSBAGAGE NOT NULL
  CONSTRAINT CK_PASS_POIDSBAGAGE CHECK (PASS_POIDSBAGAGE <= 28),  --06
PASS_DATE_NAISSANCE DATE,
PASS_NOM VARCHAR2(50)
  CONSTRAINT NN_PASS_NOM NOT NULL, 
PASS_PRENOM VARCHAR2(50)
  CONSTRAINT NN_PASS_PRENOM NOT NULL,
);



-----
CREATE TABLE HS_CLIENT(

CLI_ID NUMBER(8)
  CONSTRAINT PK_HS_CLIENT PRIMARY KEY,
CLI_ADR_ID NUMBER(4)
  CONSTRAINT   FK_CLI_ADR REFERENCES HS_ADRESSE(ADR_ID),
CLI_DATEINSCRIPTION DATE,
CLI_ACTIVE VARCHAR2(50),
CLI_NOM VARCHAR2(50)
  CONSTRAINT NN_CLI_NOM NOT NULL,
CLI_PRENOM VARCHAR2(50)
  CONSTRAINT NN_CLI_PRENOM NOT NULL,
CLI_TEL VARCHAR2(17)
  CONSTRAINT NN_CLI_TEL NOT NULL
  CONSTRAINT CK__CLI_TEL CHECK (CLI_TEL LIKE '+41.__.___.__.__'), --02
CLI_EMAIL VARCHAR2(50)
  CONSTRAINT NN_CLI_EMAIL NOT NULL
  CONSTRAINT CK__CLI_EMAIL CHECK (CLI_EMAIL LIKE '%@%.%') --03
CLI_MOTS_DE_PASSE VARCHAR2(50)
  CONSTRAINT CLI_MOTS_DE_PASSE NOT NULL 
);



-----
CREATE TABLE HS_VILLE(
VIL_ID NUMBER(4)
  CONSTRAINT PK_HS_VILLE PRIMARY KEY,
VIL_CODE NUMBER(6),
VIL_NOM VARCHAR2(50)
);








----
CREATE TABLE HS_RESERVATION(
RES_ID NUMBER(6)
  CONSTRAINT PK_HS_RESERVATION PRIMARY KEY,
VIL_ID_DE NUMBER(4)
  CONSTRAINT   FK_VILLE_DE_RESERVATOIN REFERENCES HS_VILLE(VIL_ID),
VIL_ID_POUR NUMBER(4)
  CONSTRAINT   FK_VILLE_POUR_RESERVATOIN REFERENCES HS_VILLE(VIL_ID),
CLI_RES_ID NUMBER(8)
  CONSTRAINT   FK_CLIENT_RESERVATOIN REFERENCES HS_CLIENT(CLI_ID),
RES_DATE_RESERVATION DATE,
RES_DUREEESTIME NUMBER(10),
RES_ACCOMPTE NUMBER(5),
RES_STATUT VARCHAR2(50),
RES_NOMBRE_PASSAGERS_ESTIMEE NUMBER(2) --07
  CONSTRAINT CK_RES_NOMBRE_PASSAGERS_ESTIMEE CHECK (RES_NOMBRE_PASSAGERS_ESTIMEE > 0)
);




----
CREATE TABLE HS_TRAJET(
TRAJ_ID NUMBER(6)
  CONSTRAINT PK_HS_TRAJET PRIMARY KEY,
VIL_ID_DEPART NUMBER(4)
  CONSTRAINT   FK_VILLE_TRAJET REFERENCES HS_VILLE(VIL_ID),
RES_TRAJET_ID NUMBER(6)
  CONSTRAINT FK_RES_TRAJET REFERENCES HS_RESERVATION(RES_ID),
HELI_TRAJET_ID NUMBER(4)
  CONSTRAINT   FK_HELI_TRAJET REFERENCES HS_HELICOPTERE(HELI_ID),
VIL_ID_ARRIVER NUMBER(4)
   CONSTRAINT FK_VIL_ID_ARRIVER REFERENCES HS_VILLE(VIL_ID),
TRAJ_DATE_EFFECTIF DATE,
TRAJ_DUREEESTIME NUMBER(10),
TRAJ_DATEPREVUE DATE,
TRAJ_FACTURE_MONTANT VARCHAR2(5),
TRAJ_PASSAGERS_PRESENTS NUMBER(2),
TRAJ_POIDS_TOTAL NUMBER(4)

);

------
CREATE TABLE HS_PASSAGERS_TRAJETS(
PASS_ID NUMBER(8)
  CONSTRAINT   FK_PASS_TRAJET REFERENCES HS_PASSAGERS(PASS_ID),
TRAJ_ID NUMBER(6)
  CONSTRAINT   FK_PASS_TRAJ REFERENCES HS_TRAJET(TRAJ_ID),
POIDSBAGAGES NUMBER(4),
POIDSPASSAGERS NUMBER(4)
);

-----


 
